/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nicta.com.au.patent.document;

import java.util.Arrays;
import java.util.List;
import org.apache.lucene.analysis.util.CharArraySet;
import org.apache.lucene.util.Version;

/**
 * 
 * @author rbouadjenek
 */
public class PatentsStopWords {

	/**
	 * An unmodifiable set containing some common English words that are not
	 * usually useful for patent search.
	 */
	public static final CharArraySet TITLE_ENGLISH_STOP_WORDS_SET;

	static {
		final List<String> stopWords = Arrays.asList("a", "a's", "able",
				"about", "above", "according", "accordingly", "across",
				"actually", "after", "afterwards", "again", "against", "ain't",
				"all", "allow", "allows", "almost", "alone", "along",
				"already", "also", "although", "always", "am", "among",
				"amongst", "an", "and", "another", "any", "anybody", "anyhow",
				"anyone", "anything", "anyway", "anyways", "anywhere", "apart",
				"appear", "appreciate", "appropriate", "are", "aren't",
				"around", "as", "aside", "ask", "asking", "associated", "at",
				"available", "away", "awfully", "b", "be", "became", "because",
				"become", "becomes", "becoming", "been", "before",
				"beforehand", "behind", "being", "believe", "below", "beside",
				"besides", "best", "better", "between", "beyond", "both",
				"brief", "but", "by", "c", "c'mon", "c's", "came", "can",
				"can't", "cannot", "cant", "cause", "causes", "certain",
				"certainly", "changes", "clearly", "co", "com", "come",
				"comes", "concerning", "consequently", "consider",
				"considering", "contain", "containing", "contains",
				"corresponding", "could", "couldn't", "course", "currently",
				"d", "definitely", "described", "despite", "did", "didn't",
				"different", "do", "does", "doesn't", "doing", "don't", "done",
				"down", "downwards", "during", "e", "each", "edu", "eg",
				"eight", "either", "else", "elsewhere", "enough", "entirely",
				"especially", "et", "etc", "even", "ever", "every",
				"everybody", "everyone", "everything", "everywhere", "ex",
				"exactly", "example", "except", "f", "far", "few", "fifth",
				"first", "five", "followed", "following", "follows", "for",
				"former", "formerly", "forth", "four", "from", "further",
				"furthermore", "g", "get", "gets", "getting", "given", "gives",
				"go", "goes", "going", "gone", "got", "gotten", "greetings",
				"h", "had", "hadn't", "happens", "hardly", "has", "hasn't",
				"have", "haven't", "having", "he", "he's", "hello", "help",
				"hence", "her", "here", "here's", "hereafter", "hereby",
				"herein", "hereupon", "hers", "herself", "hi", "him",
				"himself", "his", "hither", "hopefully", "how", "howbeit",
				"however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if",
				"ignored", "immediate", "in", "inasmuch", "inc", "indeed",
				"indicate", "indicated", "indicates", "inner", "insofar",
				"instead", "into", "inward", "is", "isn't", "it", "it'd",
				"it'll", "it's", "its", "itself", "j", "just", "k", "keep",
				"keeps", "kept", "know", "knows", "known", "l", "last",
				"lately", "later", "latter", "latterly", "least", "less",
				"lest", "let", "let's", "like", "liked", "likely", "little",
				"look", "looking", "looks", "ltd", "m", "mainly", "many",
				"may", "maybe", "me", "mean", "meanwhile", "merely", "might",
				"more", "moreover", "most", "mostly", "much", "must", "my",
				"myself", "n", "name", "namely", "nd", "near", "nearly",
				"necessary", "need", "needs", "neither", "never",
				"nevertheless", "new", "next", "nine", "no", "nobody", "non",
				"none", "noone", "nor", "normally", "not", "nothing", "novel",
				"now", "nowhere", "o", "obviously", "of", "off", "often", "oh",
				"ok", "okay", "old", "on", "once", "one", "ones", "only",
				"onto", "or", "other", "others", "otherwise", "ought", "our",
				"ours", "ourselves", "out", "outside", "over", "overall",
				"own", "p", "particular", "particularly", "per", "perhaps",
				"placed", "please", "plus", "possible", "presumably",
				"probably", "provides", "q", "que", "quite", "qv", "r",
				"rather", "rd", "re", "really", "reasonably", "regarding",
				"regardless", "regards", "relatively", "respectively", "right",
				"s", "said", "same", "saw", "say", "saying", "says", "second",
				"secondly", "see", "seeing", "seem", "seemed", "seeming",
				"seems", "seen", "self", "selves", "sensible", "sent",
				"serious", "seriously", "seven", "several", "shall", "she",
				"should", "shouldn't", "since", "six", "so", "some",
				"somebody", "somehow", "someone", "something", "sometime",
				"sometimes", "somewhat", "somewhere", "soon", "sorry",
				"specified", "specify", "specifying", "still", "sub", "such",
				"sup", "sure", "t", "t's", "take", "taken", "tell", "tends",
				"th", "than", "thank", "thanks", "thanx", "that", "that's",
				"thats", "the", "their", "theirs", "them", "themselves",
				"then", "thence", "there", "there's", "thereafter", "thereby",
				"therefore", "therein", "theres", "thereupon", "these", "they",
				"they'd", "they'll", "they're", "they've", "think", "third",
				"this", "thorough", "thoroughly", "those", "though", "three",
				"through", "throughout", "thru", "thus", "to", "together",
				"too", "took", "toward", "towards", "tried", "tries", "truly",
				"try", "trying", "twice", "two", "u", "un", "under",
				"unfortunately", "unless", "unlikely", "until", "unto", "up",
				"upon", "us", "use", "used", "useful", "uses", "using",
				"usually", "uucp", "v", "value", "various", "very", "via",
				"viz", "vs", "w", "want", "wants", "was", "wasn't", "way",
				"we", "we'd", "we'll", "we're", "we've", "welcome", "well",
				"went", "were", "weren't", "what", "what's", "whatever",
				"when", "whence", "whenever", "where", "where's", "whereafter",
				"whereas", "whereby", "wherein", "whereupon", "wherever",
				"whether", "which", "while", "whither", "who", "who's",
				"whoever", "whole", "whom", "whose", "why", "will", "willing",
				"wish", "with", "within", "without", "won't", "wonder",
				"would", "would", "wouldn't", "x", "y", "yes", "yet", "you",
				"you'd", "you'll", "you're", "you've", "your", "yours",
				
				"method", "device", "apparatus", "system", "process"
				);
		final CharArraySet stopSet = new CharArraySet(Version.LUCENE_48,
				stopWords, false);
		TITLE_ENGLISH_STOP_WORDS_SET = CharArraySet.unmodifiableSet(stopSet);
	}

	public static final CharArraySet ABSTRACT_ENGLISH_STOP_WORDS_SET;

	static {
		final List<String> stopWords = Arrays.asList("a", "a's", "able",
				"about", "above", "according", "accordingly", "across",
				"actually", "after", "afterwards", "again", "against", "ain't",
				"all", "allow", "allows", "almost", "alone", "along",
				"already", "also", "although", "always", "am", "among",
				"amongst", "an", "and", "another", "any", "anybody", "anyhow",
				"anyone", "anything", "anyway", "anyways", "anywhere", "apart",
				"appear", "appreciate", "appropriate", "are", "aren't",
				"around", "as", "aside", "ask", "asking", "associated", "at",
				"available", "away", "awfully", "b", "be", "became", "because",
				"become", "becomes", "becoming", "been", "before",
				"beforehand", "behind", "being", "believe", "below", "beside",
				"besides", "best", "better", "between", "beyond", "both",
				"brief", "but", "by", "c", "c'mon", "c's", "came", "can",
				"can't", "cannot", "cant", "cause", "causes", "certain",
				"certainly", "changes", "clearly", "co", "com", "come",
				"comes", "concerning", "consequently", "consider",
				"considering", "contain", "containing", "contains",
				"corresponding", "could", "couldn't", "course", "currently",
				"d", "definitely", "described", "despite", "did", "didn't",
				"different", "do", "does", "doesn't", "doing", "don't", "done",
				"down", "downwards", "during", "e", "each", "edu", "eg",
				"eight", "either", "else", "elsewhere", "enough", "entirely",
				"especially", "et", "etc", "even", "ever", "every",
				"everybody", "everyone", "everything", "everywhere", "ex",
				"exactly", "example", "except", "f", "far", "few", "fifth",
				"first", "five", "followed", "following", "follows", "for",
				"former", "formerly", "forth", "four", "from", "further",
				"furthermore", "g", "get", "gets", "getting", "given", "gives",
				"go", "goes", "going", "gone", "got", "gotten", "greetings",
				"h", "had", "hadn't", "happens", "hardly", "has", "hasn't",
				"have", "haven't", "having", "he", "he's", "hello", "help",
				"hence", "her", "here", "here's", "hereafter", "hereby",
				"herein", "hereupon", "hers", "herself", "hi", "him",
				"himself", "his", "hither", "hopefully", "how", "howbeit",
				"however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if",
				"ignored", "immediate", "in", "inasmuch", "inc", "indeed",
				"indicate", "indicated", "indicates", "inner", "insofar",
				"instead", "into", "inward", "is", "isn't", "it", "it'd",
				"it'll", "it's", "its", "itself", "j", "just", "k", "keep",
				"keeps", "kept", "know", "knows", "known", "l", "last",
				"lately", "later", "latter", "latterly", "least", "less",
				"lest", "let", "let's", "like", "liked", "likely", "little",
				"look", "looking", "looks", "ltd", "m", "mainly", "many",
				"may", "maybe", "me", "mean", "meanwhile", "merely", "might",
				"more", "moreover", "most", "mostly", "much", "must", "my",
				"myself", "n", "name", "namely", "nd", "near", "nearly",
				"necessary", "need", "needs", "neither", "never",
				"nevertheless", "new", "next", "nine", "no", "nobody", "non",
				"none", "noone", "nor", "normally", "not", "nothing", "novel",
				"now", "nowhere", "o", "obviously", "of", "off", "often", "oh",
				"ok", "okay", "old", "on", "once", "one", "ones", "only",
				"onto", "or", "other", "others", "otherwise", "ought", "our",
				"ours", "ourselves", "out", "outside", "over", "overall",
				"own", "p", "particular", "particularly", "per", "perhaps",
				"placed", "please", "plus", "possible", "presumably",
				"probably", "provides", "q", "que", "quite", "qv", "r",
				"rather", "rd", "re", "really", "reasonably", "regarding",
				"regardless", "regards", "relatively", "respectively", "right",
				"s", "said", "same", "saw", "say", "saying", "says", "second",
				"secondly", "see", "seeing", "seem", "seemed", "seeming",
				"seems", "seen", "self", "selves", "sensible", "sent",
				"serious", "seriously", "seven", "several", "shall", "she",
				"should", "shouldn't", "since", "six", "so", "some",
				"somebody", "somehow", "someone", "something", "sometime",
				"sometimes", "somewhat", "somewhere", "soon", "sorry",
				"specified", "specify", "specifying", "still", "sub", "such",
				"sup", "sure", "t", "t's", "take", "taken", "tell", "tends",
				"th", "than", "thank", "thanks", "thanx", "that", "that's",
				"thats", "the", "their", "theirs", "them", "themselves",
				"then", "thence", "there", "there's", "thereafter", "thereby",
				"therefore", "therein", "theres", "thereupon", "these", "they",
				"they'd", "they'll", "they're", "they've", "think", "third",
				"this", "thorough", "thoroughly", "those", "though", "three",
				"through", "throughout", "thru", "thus", "to", "together",
				"too", "took", "toward", "towards", "tried", "tries", "truly",
				"try", "trying", "twice", "two", "u", "un", "under",
				"unfortunately", "unless", "unlikely", "until", "unto", "up",
				"upon", "us", "use", "used", "useful", "uses", "using",
				"usually", "uucp", "v", "value", "various", "very", "via",
				"viz", "vs", "w", "want", "wants", "was", "wasn't", "way",
				"we", "we'd", "we'll", "we're", "we've", "welcome", "well",
				"went", "were", "weren't", "what", "what's", "whatever",
				"when", "whence", "whenever", "where", "where's", "whereafter",
				"whereas", "whereby", "wherein", "whereupon", "wherever",
				"whether", "which", "while", "whither", "who", "who's",
				"whoever", "whole", "whom", "whose", "why", "will", "willing",
				"wish", "with", "within", "without", "won't", "wonder",
				"would", "would", "wouldn't", "x", "y", "yes", "yet", "you",
				"you'd", "you'll", "you're", "you've", "your", "yours",
				
				"which", "from", "one", "having", "first", "said", "least",
				"invention", "device", "each", "can", "has", "second", "means",
				"between", "surface", "provided", "signal", "method", "system"
				);
		final CharArraySet stopSet = new CharArraySet(Version.LUCENE_48,
				stopWords, false);
		ABSTRACT_ENGLISH_STOP_WORDS_SET = CharArraySet.unmodifiableSet(stopSet);
	}

	public static final CharArraySet DESCRIPTION_ENGLISH_STOP_WORDS_SET;

	static {
		final List<String> stopWords = Arrays.asList("a", "a's", "able",
				"about", "above", "according", "accordingly", "across",
				"actually", "after", "afterwards", "again", "against", "ain't",
				"all", "allow", "allows", "almost", "alone", "along",
				"already", "also", "although", "always", "am", "among",
				"amongst", "an", "and", "another", "any", "anybody", "anyhow",
				"anyone", "anything", "anyway", "anyways", "anywhere", "apart",
				"appear", "appreciate", "appropriate", "are", "aren't",
				"around", "as", "aside", "ask", "asking", "associated", "at",
				"available", "away", "awfully", "b", "be", "became", "because",
				"become", "becomes", "becoming", "been", "before",
				"beforehand", "behind", "being", "believe", "below", "beside",
				"besides", "best", "better", "between", "beyond", "both",
				"brief", "but", "by", "c", "c'mon", "c's", "came", "can",
				"can't", "cannot", "cant", "cause", "causes", "certain",
				"certainly", "changes", "clearly", "co", "com", "come",
				"comes", "concerning", "consequently", "consider",
				"considering", "contain", "containing", "contains",
				"corresponding", "could", "couldn't", "course", "currently",
				"d", "definitely", "described", "despite", "did", "didn't",
				"different", "do", "does", "doesn't", "doing", "don't", "done",
				"down", "downwards", "during", "e", "each", "edu", "eg",
				"eight", "either", "else", "elsewhere", "enough", "entirely",
				"especially", "et", "etc", "even", "ever", "every",
				"everybody", "everyone", "everything", "everywhere", "ex",
				"exactly", "example", "except", "f", "far", "few", "fifth",
				"first", "five", "followed", "following", "follows", "for",
				"former", "formerly", "forth", "four", "from", "further",
				"furthermore", "g", "get", "gets", "getting", "given", "gives",
				"go", "goes", "going", "gone", "got", "gotten", "greetings",
				"h", "had", "hadn't", "happens", "hardly", "has", "hasn't",
				"have", "haven't", "having", "he", "he's", "hello", "help",
				"hence", "her", "here", "here's", "hereafter", "hereby",
				"herein", "hereupon", "hers", "herself", "hi", "him",
				"himself", "his", "hither", "hopefully", "how", "howbeit",
				"however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if",
				"ignored", "immediate", "in", "inasmuch", "inc", "indeed",
				"indicate", "indicated", "indicates", "inner", "insofar",
				"instead", "into", "inward", "is", "isn't", "it", "it'd",
				"it'll", "it's", "its", "itself", "j", "just", "k", "keep",
				"keeps", "kept", "know", "knows", "known", "l", "last",
				"lately", "later", "latter", "latterly", "least", "less",
				"lest", "let", "let's", "like", "liked", "likely", "little",
				"look", "looking", "looks", "ltd", "m", "mainly", "many",
				"may", "maybe", "me", "mean", "meanwhile", "merely", "might",
				"more", "moreover", "most", "mostly", "much", "must", "my",
				"myself", "n", "name", "namely", "nd", "near", "nearly",
				"necessary", "need", "needs", "neither", "never",
				"nevertheless", "new", "next", "nine", "no", "nobody", "non",
				"none", "noone", "nor", "normally", "not", "nothing", "novel",
				"now", "nowhere", "o", "obviously", "of", "off", "often", "oh",
				"ok", "okay", "old", "on", "once", "one", "ones", "only",
				"onto", "or", "other", "others", "otherwise", "ought", "our",
				"ours", "ourselves", "out", "outside", "over", "overall",
				"own", "p", "particular", "particularly", "per", "perhaps",
				"placed", "please", "plus", "possible", "presumably",
				"probably", "provides", "q", "que", "quite", "qv", "r",
				"rather", "rd", "re", "really", "reasonably", "regarding",
				"regardless", "regards", "relatively", "respectively", "right",
				"s", "said", "same", "saw", "say", "saying", "says", "second",
				"secondly", "see", "seeing", "seem", "seemed", "seeming",
				"seems", "seen", "self", "selves", "sensible", "sent",
				"serious", "seriously", "seven", "several", "shall", "she",
				"should", "shouldn't", "since", "six", "so", "some",
				"somebody", "somehow", "someone", "something", "sometime",
				"sometimes", "somewhat", "somewhere", "soon", "sorry",
				"specified", "specify", "specifying", "still", "sub", "such",
				"sup", "sure", "t", "t's", "take", "taken", "tell", "tends",
				"th", "than", "thank", "thanks", "thanx", "that", "that's",
				"thats", "the", "their", "theirs", "them", "themselves",
				"then", "thence", "there", "there's", "thereafter", "thereby",
				"therefore", "therein", "theres", "thereupon", "these", "they",
				"they'd", "they'll", "they're", "they've", "think", "third",
				"this", "thorough", "thoroughly", "those", "though", "three",
				"through", "throughout", "thru", "thus", "to", "together",
				"too", "took", "toward", "towards", "tried", "tries", "truly",
				"try", "trying", "twice", "two", "u", "un", "under",
				"unfortunately", "unless", "unlikely", "until", "unto", "up",
				"upon", "us", "use", "used", "useful", "uses", "using",
				"usually", "uucp", "v", "value", "various", "very", "via",
				"viz", "vs", "w", "want", "wants", "was", "wasn't", "way",
				"we", "we'd", "we'll", "we're", "we've", "welcome", "well",
				"went", "were", "weren't", "what", "what's", "whatever",
				"when", "whence", "whenever", "where", "where's", "whereafter",
				"whereas", "whereby", "wherein", "whereupon", "wherever",
				"whether", "which", "while", "whither", "who", "who's",
				"whoever", "whole", "whom", "whose", "why", "will", "willing",
				"wish", "with", "within", "without", "won't", "wonder",
				"would", "would", "wouldn't", "x", "y", "yes", "yet", "you",
				"you'd", "you'll", "you're", "you've", "your", "yours", 
				
				"from",	"which", "invention", "can", "may", "fig", "one", "present",
				"c", "example", "used", "data", "each", "other", "has", "when",
				"also", "first", "shown", "signal", "figure", "acid",
				"between", "system", "described", "about", "n", "embodiment",
				"more", "having", "surface", "second", "were", "preferably",
				"above", "through", "m", "control", "means", "layer",
				"portion", "have", "using", "than", "two", "time", "material",
				"g", "device", "so", "method", "according", "end",
				"temperature", "s", "group", "water", "been", "d", "further",
				"b", "solution", "use", "step", "high", "provided", "after",
				"same", "process", "said", "preferred", "form", "its",
				"formed", "i", "any", "position", "number", "pressure", "h",
				"unit", "side", "type", "output", "weight", "thus", "being",
				"l", "light", "line", "within", "least", "mixture",
				"containing", "x", "include", "e.g", "added", "all",
				"apparatus", "value", "reference", "where", "obtained", "view",
				"another", "out", "amount", "al", "known", "set", "only",
				"provide", "t", "following", "operation", "part", "under",
				"flow", "made", "lower", "r", "liquid", "includes", "during",
				"base", "case", "product", "section", "connected", "direction",
				"however", "table", "over", "both", "structure", "like",
				"wherein", "different", "well", "block", "power", "body",
				"low", "art", "suitable", "metal", "thereof", "air", "while",
				"those", "processing", "order", "selected", "non", "p",
				"current", "shows", "up", "phase", "comprises", "level",
				"addition", "desired", "comprising", "range", "area", "point",
				"applied", "based", "examples", "prepared", "corresponding",
				"including", "generally", "state", "mm", "patent",
				"particular", "application", "rate", "length", "specific",
				"therefore", "less", "source", "without", "single", "e",
				"provides", "component", "possible", "below", "contact",
				"herein", "object", "various", "methods", "support", "three",
				"manner", "results", "result", "parts", "size", "upper",
				"accordance", "components", "materials", "along",
				"substantially", "conventional", "since", "elements",
				"conditions", "i.e", "either", "particularly", "field",
				"function", "cross", "respectively", "determined", "solid",
				"via", "some", "f", "required", "plurality", "because",
				"should", "ratio", "would", "defined", "figs", "embodiments",
				"upon", "forming", "prior", "most", "similar", "effect",
				"illustrated", "associated", "per", "thereby", "produced",
				"way", "resulting", "diameter", "small", "description",
				"showing", "portions", "available", "top", "found",
				"performed", "reduced", "typically", "values", "large", "u.s",
				"removed", "lines", "off", "given", "relative", "systems",
				"even", "devices", "figures", "higher", "third", "greater",
				"connection", "carried", "predetermined", "total", "against",
				"limited", "period", "due", "useful", "presence", "additional",
				"relates", "together", "free", "before", "new", "measured",
				"mounted", "does", "see", "general", "employed", "properties",
				"respective", "could", "generated", "necessary", "must",
				"change", "combination", "etc", "mentioned", "shape",
				"appropriate", "located", "next", "indicated", "now", "back",
				"fixed", "respect", "very", "placed", "approximately", "steps",
				"four", "attached", "increase", "produce", "aspect",
				"characteristics", "arranged", "effective", "standard",
				"relatively", "open", "adjacent", "operating", "disclosed",
				"although", "controlled", "contain", "times", "arrangement",
				"contains", "increased", "onto", "parallel", "many",
				"condition", "capable", "long", "taken", "comprise",
				"providing", "certain", "hand", "alternatively", "normal",
				"several", "until", "accordingly", "directly", "obtain",
				"equal", "need", "techniques", "specifically", "maximum",
				"drawings", "referring", "still", "improved", "previously",
				"around", "compared", "place", "sufficient", "forms", "detail",
				"incorporated", "applications", "combined", "seen", "down",
				"furthermore", "changes", "achieved", "referred", "opposite",
				"contained", "allow", "allows", "types", "separate", "common",
				"prevent", "especially", "skilled", "usually", "once", "cause",
				"do", "understood", "becomes", "them", "depending", "show",
				"follows", "larger", "make", "problem", "features", "short",
				"again", "included", "easily", "desirable", "alternative",
				"smaller", "intended", "making", "called", "therein", "reduce",
				"scope", "noted", "significant", "complete", "important",
				"become", "purpose", "occurs", "detailed", "causes", "typical",
				"apparent", "occur", "readily", "similarly", "increasing",
				"claims", "otherwise", "problems", "often", "discloses",
				"itself", "much", "instead", "advantages", "cannot", "achieve",
				"difficult", "accompanying", "modifications"

		);
		final CharArraySet stopSet = new CharArraySet(Version.LUCENE_48,
				stopWords, false);
		DESCRIPTION_ENGLISH_STOP_WORDS_SET = CharArraySet
				.unmodifiableSet(stopSet);
	}

	public static final CharArraySet CLAIMS_ENGLISH_STOP_WORDS_SET;

	static {
		final List<String> stopWords = Arrays.asList("a", "a's", "able",
				"about", "above", "according", "accordingly", "across",
				"actually", "after", "afterwards", "again", "against", "ain't",
				"all", "allow", "allows", "almost", "alone", "along",
				"already", "also", "although", "always", "am", "among",
				"amongst", "an", "and", "another", "any", "anybody", "anyhow",
				"anyone", "anything", "anyway", "anyways", "anywhere", "apart",
				"appear", "appreciate", "appropriate", "are", "aren't",
				"around", "as", "aside", "ask", "asking", "associated", "at",
				"available", "away", "awfully", "b", "be", "became", "because",
				"become", "becomes", "becoming", "been", "before",
				"beforehand", "behind", "being", "believe", "below", "beside",
				"besides", "best", "better", "between", "beyond", "both",
				"brief", "but", "by", "c", "c'mon", "c's", "came", "can",
				"can't", "cannot", "cant", "cause", "causes", "certain",
				"certainly", "changes", "clearly", "co", "com", "come",
				"comes", "concerning", "consequently", "consider",
				"considering", "contain", "containing", "contains",
				"corresponding", "could", "couldn't", "course", "currently",
				"d", "definitely", "described", "despite", "did", "didn't",
				"different", "do", "does", "doesn't", "doing", "don't", "done",
				"down", "downwards", "during", "e", "each", "edu", "eg",
				"eight", "either", "else", "elsewhere", "enough", "entirely",
				"especially", "et", "etc", "even", "ever", "every",
				"everybody", "everyone", "everything", "everywhere", "ex",
				"exactly", "example", "except", "f", "far", "few", "fifth",
				"first", "five", "followed", "following", "follows", "for",
				"former", "formerly", "forth", "four", "from", "further",
				"furthermore", "g", "get", "gets", "getting", "given", "gives",
				"go", "goes", "going", "gone", "got", "gotten", "greetings",
				"h", "had", "hadn't", "happens", "hardly", "has", "hasn't",
				"have", "haven't", "having", "he", "he's", "hello", "help",
				"hence", "her", "here", "here's", "hereafter", "hereby",
				"herein", "hereupon", "hers", "herself", "hi", "him",
				"himself", "his", "hither", "hopefully", "how", "howbeit",
				"however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if",
				"ignored", "immediate", "in", "inasmuch", "inc", "indeed",
				"indicate", "indicated", "indicates", "inner", "insofar",
				"instead", "into", "inward", "is", "isn't", "it", "it'd",
				"it'll", "it's", "its", "itself", "j", "just", "k", "keep",
				"keeps", "kept", "know", "knows", "known", "l", "last",
				"lately", "later", "latter", "latterly", "least", "less",
				"lest", "let", "let's", "like", "liked", "likely", "little",
				"look", "looking", "looks", "ltd", "m", "mainly", "many",
				"may", "maybe", "me", "mean", "meanwhile", "merely", "might",
				"more", "moreover", "most", "mostly", "much", "must", "my",
				"myself", "n", "name", "namely", "nd", "near", "nearly",
				"necessary", "need", "needs", "neither", "never",
				"nevertheless", "new", "next", "nine", "no", "nobody", "non",
				"none", "noone", "nor", "normally", "not", "nothing", "novel",
				"now", "nowhere", "o", "obviously", "of", "off", "often", "oh",
				"ok", "okay", "old", "on", "once", "one", "ones", "only",
				"onto", "or", "other", "others", "otherwise", "ought", "our",
				"ours", "ourselves", "out", "outside", "over", "overall",
				"own", "p", "particular", "particularly", "per", "perhaps",
				"placed", "please", "plus", "possible", "presumably",
				"probably", "provides", "q", "que", "quite", "qv", "r",
				"rather", "rd", "re", "really", "reasonably", "regarding",
				"regardless", "regards", "relatively", "respectively", "right",
				"s", "said", "same", "saw", "say", "saying", "says", "second",
				"secondly", "see", "seeing", "seem", "seemed", "seeming",
				"seems", "seen", "self", "selves", "sensible", "sent",
				"serious", "seriously", "seven", "several", "shall", "she",
				"should", "shouldn't", "since", "six", "so", "some",
				"somebody", "somehow", "someone", "something", "sometime",
				"sometimes", "somewhat", "somewhere", "soon", "sorry",
				"specified", "specify", "specifying", "still", "sub", "such",
				"sup", "sure", "t", "t's", "take", "taken", "tell", "tends",
				"th", "than", "thank", "thanks", "thanx", "that", "that's",
				"thats", "the", "their", "theirs", "them", "themselves",
				"then", "thence", "there", "there's", "thereafter", "thereby",
				"therefore", "therein", "theres", "thereupon", "these", "they",
				"they'd", "they'll", "they're", "they've", "think", "third",
				"this", "thorough", "thoroughly", "those", "though", "three",
				"through", "throughout", "thru", "thus", "to", "together",
				"too", "took", "toward", "towards", "tried", "tries", "truly",
				"try", "trying", "twice", "two", "u", "un", "under",
				"unfortunately", "unless", "unlikely", "until", "unto", "up",
				"upon", "us", "use", "used", "useful", "uses", "using",
				"usually", "uucp", "v", "value", "various", "very", "via",
				"viz", "vs", "w", "want", "wants", "was", "wasn't", "way",
				"we", "we'd", "we'll", "we're", "we've", "welcome", "well",
				"went", "were", "weren't", "what", "what's", "whatever",
				"when", "whence", "whenever", "where", "where's", "whereafter",
				"whereas", "whereby", "wherein", "whereupon", "wherever",
				"whether", "which", "while", "whither", "who", "who's",
				"whoever", "whole", "whom", "whose", "why", "will", "willing",
				"wish", "with", "within", "without", "won't", "wonder",
				"would", "would", "wouldn't", "x", "y", "yes", "yet", "you",
				"you'd", "you'll", "you're", "you've", "your", "yours", 
				
				"said", "claim", "wherein", "according", "one", "from", "means",
				"which", "first", "second", "method", "comprise", "comprising",
				"least", "claims", "having", "each", "any", "c",
				"characterized", "comprises", "device", "group", "signal",
				"being", "data", "system", "between", "further", "apparatus",
				"claimed", "surface", "portion", "selected", "n", "process",
				"end", "material", "r", "characterised", "member", "plurality",
				"has", "about", "control", "acid", "layer", "step",
				"composition", "compound", "alkyl", "b", "position", "two",
				"than", "element"
				);
		final CharArraySet stopSet = new CharArraySet(Version.LUCENE_48,
				stopWords, false);
		CLAIMS_ENGLISH_STOP_WORDS_SET = CharArraySet.unmodifiableSet(stopSet);
	}

	public static final CharArraySet ENGLISH_STOP_WORDS_SET;

	static {
		final List<String> stopWords = Arrays.asList("a", "a's", "able",
				"about", "above", "according", "accordingly", "across",
				"actually", "after", "afterwards", "again", "against", "ain't",
				"all", "allow", "allows", "almost", "alone", "along",
				"already", "also", "although", "always", "am", "among",
				"amongst", "an", "and", "another", "any", "anybody", "anyhow",
				"anyone", "anything", "anyway", "anyways", "anywhere", "apart",
				"appear", "appreciate", "appropriate", "are", "aren't",
				"around", "as", "aside", "ask", "asking", "associated", "at",
				"available", "away", "awfully", "b", "be", "became", "because",
				"become", "becomes", "becoming", "been", "before",
				"beforehand", "behind", "being", "believe", "below", "beside",
				"besides", "best", "better", "between", "beyond", "both",
				"brief", "but", "by", "c", "c'mon", "c's", "came", "can",
				"can't", "cannot", "cant", "cause", "causes", "certain",
				"certainly", "changes", "clearly", "co", "com", "come",
				"comes", "concerning", "consequently", "consider",
				"considering", "contain", "containing", "contains",
				"corresponding", "could", "couldn't", "course", "currently",
				"d", "definitely", "described", "despite", "did", "didn't",
				"different", "do", "does", "doesn't", "doing", "don't", "done",
				"down", "downwards", "during", "e", "each", "edu", "eg",
				"eight", "either", "else", "elsewhere", "enough", "entirely",
				"especially", "et", "etc", "even", "ever", "every",
				"everybody", "everyone", "everything", "everywhere", "ex",
				"exactly", "example", "except", "f", "far", "few", "fifth",
				"first", "five", "followed", "following", "follows", "for",
				"former", "formerly", "forth", "four", "from", "further",
				"furthermore", "g", "get", "gets", "getting", "given", "gives",
				"go", "goes", "going", "gone", "got", "gotten", "greetings",
				"h", "had", "hadn't", "happens", "hardly", "has", "hasn't",
				"have", "haven't", "having", "he", "he's", "hello", "help",
				"hence", "her", "here", "here's", "hereafter", "hereby",
				"herein", "hereupon", "hers", "herself", "hi", "him",
				"himself", "his", "hither", "hopefully", "how", "howbeit",
				"however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if",
				"ignored", "immediate", "in", "inasmuch", "inc", "indeed",
				"indicate", "indicated", "indicates", "inner", "insofar",
				"instead", "into", "inward", "is", "isn't", "it", "it'd",
				"it'll", "it's", "its", "itself", "j", "just", "k", "keep",
				"keeps", "kept", "know", "knows", "known", "l", "last",
				"lately", "later", "latter", "latterly", "least", "less",
				"lest", "let", "let's", "like", "liked", "likely", "little",
				"look", "looking", "looks", "ltd", "m", "mainly", "many",
				"may", "maybe", "me", "mean", "meanwhile", "merely", "might",
				"more", "moreover", "most", "mostly", "much", "must", "my",
				"myself", "n", "name", "namely", "nd", "near", "nearly",
				"necessary", "need", "needs", "neither", "never",
				"nevertheless", "new", "next", "nine", "no", "nobody", "non",
				"none", "noone", "nor", "normally", "not", "nothing", "novel",
				"now", "nowhere", "o", "obviously", "of", "off", "often", "oh",
				"ok", "okay", "old", "on", "once", "one", "ones", "only",
				"onto", "or", "other", "others", "otherwise", "ought", "our",
				"ours", "ourselves", "out", "outside", "over", "overall",
				"own", "p", "particular", "particularly", "per", "perhaps",
				"placed", "please", "plus", "possible", "presumably",
				"probably", "provides", "q", "que", "quite", "qv", "r",
				"rather", "rd", "re", "really", "reasonably", "regarding",
				"regardless", "regards", "relatively", "respectively", "right",
				"s", "said", "same", "saw", "say", "saying", "says", "second",
				"secondly", "see", "seeing", "seem", "seemed", "seeming",
				"seems", "seen", "self", "selves", "sensible", "sent",
				"serious", "seriously", "seven", "several", "shall", "she",
				"should", "shouldn't", "since", "six", "so", "some",
				"somebody", "somehow", "someone", "something", "sometime",
				"sometimes", "somewhat", "somewhere", "soon", "sorry",
				"specified", "specify", "specifying", "still", "sub", "such",
				"sup", "sure", "t", "t's", "take", "taken", "tell", "tends",
				"th", "than", "thank", "thanks", "thanx", "that", "that's",
				"thats", "the", "their", "theirs", "them", "themselves",
				"then", "thence", "there", "there's", "thereafter", "thereby",
				"therefore", "therein", "theres", "thereupon", "these", "they",
				"they'd", "they'll", "they're", "they've", "think", "third",
				"this", "thorough", "thoroughly", "those", "though", "three",
				"through", "throughout", "thru", "thus", "to", "together",
				"too", "took", "toward", "towards", "tried", "tries", "truly",
				"try", "trying", "twice", "two", "u", "un", "under",
				"unfortunately", "unless", "unlikely", "until", "unto", "up",
				"upon", "us", "use", "used", "useful", "uses", "using",
				"usually", "uucp", "v", "value", "various", "very", "via",
				"viz", "vs", "w", "want", "wants", "was", "wasn't", "way",
				"we", "we'd", "we'll", "we're", "we've", "welcome", "well",
				"went", "were", "weren't", "what", "what's", "whatever",
				"when", "whence", "whenever", "where", "where's", "whereafter",
				"whereas", "whereby", "wherein", "whereupon", "wherever",
				"whether", "which", "while", "whither", "who", "who's",
				"whoever", "whole", "whom", "whose", "why", "will", "willing",
				"wish", "with", "within", "without", "won't", "wonder",
				"would", "would", "wouldn't", "x", "y", "yes", "yet", "you",
				"you'd", "you'll", "you're", "you've", "your", "yours");
		final CharArraySet stopSet = new CharArraySet(Version.LUCENE_48,
				stopWords, false);
		ENGLISH_STOP_WORDS_SET = CharArraySet.unmodifiableSet(stopSet);
	}

	public static final CharArraySet UNIFIED_PATENT__ENGLISH_STOP_WORDS_SET;

	static {
		final List<String> stopWords = Arrays.asList("a", "a's", "able",
				"about", "above", "according", "accordingly", "across",
				"actually", "after", "afterwards", "again", "against", "ain't",
				"all", "allow", "allows", "almost", "alone", "along",
				"already", "also", "although", "always", "am", "among",
				"amongst", "an", "and", "another", "any", "anybody", "anyhow",
				"anyone", "anything", "anyway", "anyways", "anywhere", "apart",
				"appear", "appreciate", "appropriate", "are", "aren't",
				"around", "as", "aside", "ask", "asking", "associated", "at",
				"available", "away", "awfully", "b", "be", "became", "because",
				"become", "becomes", "becoming", "been", "before",
				"beforehand", "behind", "being", "believe", "below", "beside",
				"besides", "best", "better", "between", "beyond", "both",
				"brief", "but", "by", "c", "c'mon", "c's", "came", "can",
				"can't", "cannot", "cant", "cause", "causes", "certain",
				"certainly", "changes", "clearly", "co", "com", "come",
				"comes", "concerning", "consequently", "consider",
				"considering", "contain", "containing", "contains",
				"corresponding", "could", "couldn't", "course", "currently",
				"d", "definitely", "described", "despite", "did", "didn't",
				"different", "do", "does", "doesn't", "doing", "don't", "done",
				"down", "downwards", "during", "e", "each", "edu", "eg",
				"eight", "either", "else", "elsewhere", "enough", "entirely",
				"especially", "et", "etc", "even", "ever", "every",
				"everybody", "everyone", "everything", "everywhere", "ex",
				"exactly", "example", "except", "f", "far", "few", "fifth",
				"first", "five", "followed", "following", "follows", "for",
				"former", "formerly", "forth", "four", "from", "further",
				"furthermore", "g", "get", "gets", "getting", "given", "gives",
				"go", "goes", "going", "gone", "got", "gotten", "greetings",
				"h", "had", "hadn't", "happens", "hardly", "has", "hasn't",
				"have", "haven't", "having", "he", "he's", "hello", "help",
				"hence", "her", "here", "here's", "hereafter", "hereby",
				"herein", "hereupon", "hers", "herself", "hi", "him",
				"himself", "his", "hither", "hopefully", "how", "howbeit",
				"however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if",
				"ignored", "immediate", "in", "inasmuch", "inc", "indeed",
				"indicate", "indicated", "indicates", "inner", "insofar",
				"instead", "into", "inward", "is", "isn't", "it", "it'd",
				"it'll", "it's", "its", "itself", "j", "just", "k", "keep",
				"keeps", "kept", "know", "knows", "known", "l", "last",
				"lately", "later", "latter", "latterly", "least", "less",
				"lest", "let", "let's", "like", "liked", "likely", "little",
				"look", "looking", "looks", "ltd", "m", "mainly", "many",
				"may", "maybe", "me", "mean", "meanwhile", "merely", "might",
				"more", "moreover", "most", "mostly", "much", "must", "my",
				"myself", "n", "name", "namely", "nd", "near", "nearly",
				"necessary", "need", "needs", "neither", "never",
				"nevertheless", "new", "next", "nine", "no", "nobody", "non",
				"none", "noone", "nor", "normally", "not", "nothing", "novel",
				"now", "nowhere", "o", "obviously", "of", "off", "often", "oh",
				"ok", "okay", "old", "on", "once", "one", "ones", "only",
				"onto", "or", "other", "others", "otherwise", "ought", "our",
				"ours", "ourselves", "out", "outside", "over", "overall",
				"own", "p", "particular", "particularly", "per", "perhaps",
				"placed", "please", "plus", "possible", "presumably",
				"probably", "provides", "q", "que", "quite", "qv", "r",
				"rather", "rd", "re", "really", "reasonably", "regarding",
				"regardless", "regards", "relatively", "respectively", "right",
				"s", "said", "same", "saw", "say", "saying", "says", "second",
				"secondly", "see", "seeing", "seem", "seemed", "seeming",
				"seems", "seen", "self", "selves", "sensible", "sent",
				"serious", "seriously", "seven", "several", "shall", "she",
				"should", "shouldn't", "since", "six", "so", "some",
				"somebody", "somehow", "someone", "something", "sometime",
				"sometimes", "somewhat", "somewhere", "soon", "sorry",
				"specified", "specify", "specifying", "still", "sub", "such",
				"sup", "sure", "t", "t's", "take", "taken", "tell", "tends",
				"th", "than", "thank", "thanks", "thanx", "that", "that's",
				"thats", "the", "their", "theirs", "them", "themselves",
				"then", "thence", "there", "there's", "thereafter", "thereby",
				"therefore", "therein", "theres", "thereupon", "these", "they",
				"they'd", "they'll", "they're", "they've", "think", "third",
				"this", "thorough", "thoroughly", "those", "though", "three",
				"through", "throughout", "thru", "thus", "to", "together",
				"too", "took", "toward", "towards", "tried", "tries", "truly",
				"try", "trying", "twice", "two", "u", "un", "under",
				"unfortunately", "unless", "unlikely", "until", "unto", "up",
				"upon", "us", "use", "used", "useful", "uses", "using",
				"usually", "uucp", "v", "value", "various", "very", "via",
				"viz", "vs", "w", "want", "wants", "was", "wasn't", "way",
				"we", "we'd", "we'll", "we're", "we've", "welcome", "well",
				"went", "were", "weren't", "what", "what's", "whatever",
				"when", "whence", "whenever", "where", "where's", "whereafter",
				"whereas", "whereby", "wherein", "whereupon", "wherever",
				"whether", "which", "while", "whither", "who", "who's",
				"whoever", "whole", "whom", "whose", "why", "will", "willing",
				"wish", "with", "within", "without", "won't", "wonder",
				"would", "would", "wouldn't", "x", "y", "yes", "yet", "you",
				"you'd", "you'll", "you're", "you've", "your", "yours",

				/* -------------merged title stopwords----------- -mona */
				"method", "device", "apparatus", "system", "process"
				/* -------------merged abstarct stopwords----------- -mona */
				, "which", "from", "one", "having", "first", "said", "least",
				"invention", "device", "each", "can", "has", "second", "means",
				"between", "surface", "provided", "signal", "method", "system"
				/* -------------merged description stopwords----------- -mona */
				, "from", "which", "invention", "can", "may", "fig", "one",
				"present", "c", "example", "used", "data", "each", "other",
				"has", "when", "also", "first", "shown", "signal", "figure",
				"acid", "between", "system", "described", "about", "n",
				"embodiment", "more", "having", "surface", "second", "were",
				"preferably", "above", "through", "m", "control", "means",
				"layer", "portion", "have", "using", "than", "two", "time",
				"material", "g", "device", "so", "method", "according", "end",
				"temperature", "s", "group", "water", "been", "d", "further",
				"b", "solution", "use", "step", "high", "provided", "after",
				"same", "process", "said", "preferred", "form", "its",
				"formed", "i", "any", "position", "number", "pressure", "h",
				"unit", "side", "type", "output", "weight", "thus", "being",
				"l", "light", "line", "within", "least", "mixture",
				"containing", "x", "include", "e.g", "added", "all",
				"apparatus", "value", "reference", "where", "obtained", "view",
				"another", "out", "amount", "al", "known", "set", "only",
				"provide", "t", "following", "operation", "part", "under",
				"flow", "made", "lower", "r", "liquid", "includes", "during",
				"base", "case", "product", "section", "connected", "direction",
				"however", "table", "over", "both", "structure", "like",
				"wherein", "different", "well", "block", "power", "body",
				"low", "art", "suitable", "metal", "thereof", "air", "while",
				"those", "processing", "order", "selected", "non", "p",
				"current", "shows", "up", "phase", "comprises", "level",
				"addition", "desired", "comprising", "range", "area", "point",
				"applied", "based", "examples", "prepared", "corresponding",
				"including", "generally", "state", "mm", "patent",
				"particular", "application", "rate", "length", "specific",
				"therefore", "less", "source", "without", "single", "e",
				"provides", "component", "possible", "below", "contact",
				"herein", "object", "various", "methods", "support", "three",
				"manner", "results", "result", "parts", "size", "upper",
				"accordance", "components", "materials", "along",
				"substantially", "conventional", "since", "elements",
				"conditions", "i.e", "either", "particularly", "field",
				"function", "cross", "respectively", "determined", "solid",
				"via", "some", "f", "required", "plurality", "because",
				"should", "ratio", "would", "defined", "figs", "embodiments",
				"upon", "forming", "prior", "most", "similar", "effect",
				"illustrated", "associated", "per", "thereby", "produced",
				"way", "resulting", "diameter", "small", "description",
				"showing", "portions", "available", "top", "found",
				"performed", "reduced", "typically", "values", "large", "u.s",
				"removed", "lines", "off", "given", "relative", "systems",
				"even", "devices", "figures", "higher", "third", "greater",
				"connection", "carried", "predetermined", "total", "against",
				"limited", "period", "due", "useful", "presence", "additional",
				"relates", "together", "free", "before", "new", "measured",
				"mounted", "does", "see", "general", "employed", "properties",
				"respective", "could", "generated", "necessary", "must",
				"change", "combination", "etc", "mentioned", "shape",
				"appropriate", "located", "next", "indicated", "now", "back",
				"fixed", "respect", "very", "placed", "approximately", "steps",
				"four", "attached", "increase", "produce", "aspect",
				"characteristics", "arranged", "effective", "standard",
				"relatively", "open", "adjacent", "operating", "disclosed",
				"although", "controlled", "contain", "times", "arrangement",
				"contains", "increased", "onto", "parallel", "many",
				"condition", "capable", "long", "taken", "comprise",
				"providing", "certain", "hand", "alternatively", "normal",
				"several", "until", "accordingly", "directly", "obtain",
				"equal", "need", "techniques", "specifically", "maximum",
				"drawings", "referring", "still", "improved", "previously",
				"around", "compared", "place", "sufficient", "forms", "detail",
				"incorporated", "applications", "combined", "seen", "down",
				"furthermore", "changes", "achieved", "referred", "opposite",
				"contained", "allow", "allows", "types", "separate", "common",
				"prevent", "especially", "skilled", "usually", "once", "cause",
				"do", "understood", "becomes", "them", "depending", "show",
				"follows", "larger", "make", "problem", "features", "short",
				"again", "included", "easily", "desirable", "alternative",
				"smaller", "intended", "making", "called", "therein", "reduce",
				"scope", "noted", "significant", "complete", "important",
				"become", "purpose", "occurs", "detailed", "causes", "typical",
				"apparent", "occur", "readily", "similarly", "increasing",
				"claims", "otherwise", "problems", "often", "discloses",
				"itself", "much", "instead", "advantages", "cannot", "achieve",
				"difficult", "accompanying", "modifications", 
				"represent","represents", "represented", "formula", "formulae"
				/* -------------merged claims stopwords----------- -mona */
				, "said", "claim", "wherein", "according", "one", "from",
				"means", "which", "first", "second", "secondary", "method", "comprise",
				"comprising", "least", "claims", "having", "each", "any", "c",
				"characterized", "comprises", "device", "group", "signal",
				"being", "data", "system", "between", "further", "apparatus",
				"claimed", "surface", "portion", "selected", "n", "process",
				"end", "material", "r", "characterised", "member", "plurality",
				"has", "about", "control", "acid", "acidic", "layer", "step",
				"composition", "compound", "alkyl", "b", "position", "two",
				"than", "element", "prefer", "preferable", "basic", "basically", "group"

				,/* --- added metric system units, symbols, prefixes, and etc -mona ---*/
				"min","max", "min.","max.",
				"kg","g", "mg",  "t",
				"s", "ms", "µs", "hr" , "hour", "hours", "h", "d", "a", "seconds",
				"g/cm", "kg/m", 
				"m", "mm", "cm", "cm²", "cm2","µm", "nm", "m²", "m2", "km", "km²", "km2", 
				"cm³", "m³", "cm3", "m3", "ha",
				"a", "ma", "Ω", 
				"k", "mole", "mol", "mmol", "cd", 
				"hz","n", "pa", "w", "c", "v", "f", "°c", "wb", 
				"t", "lm", "lx", "bq","gy", "sv", "bar", "st", "ev", "u","au","pc",
				"j", "kj", "mj", "j/kg", "j/k", 
				"ml", "l", "m/s", "km/h", "kg/m³", "kg/m3","kpa","kg·m/s²","kg·m/s2",
				"watt", "kilowatt", "kw", "kw·h", 
				"rad", "sr", "rad/s²", "rad/s2",
				"m/s²", "m/s2","1/s", "w/a",
				"i", "ii", "iii", "iv", "v", "vi", "vii",
				"viii", "ix", "x", "xi", "xii", "xiii", "xiv", "xv", "xvi",
				"xvii", "xvii", "xix", "xx", 
				"Α",    "α", 
				"Β",	"β", 
				"Γ", 	"γ",	
				"Δ",	"δ",	
				"Ε",	"ε",	
				"Ζ",	"ζ",	
				"Η",	"η",	
				"Θ",	"θ",	
				"Ι",	"ι",	
				"Κ",	"κ",	
				"Λ",	"λ",	
				"Μ",	"μ",	
				"Ν",	"ν",	
				"Ξ",	"ξ",	
				"Ο",	"ο",	
				"Π",	"π",	
				"Ρ",	"ρ",	
				"Σ",	"σ",	
				"Τ",	"τ",	
				"Υ",	"υ",	
				"Φ",	"φ",	
				"Χ",	"χ",	
				"Ψ",    "ψ",	
				"Ω",    "ω"	
				);
		final CharArraySet stopSet = new CharArraySet(Version.LUCENE_48,
				stopWords, false);
		UNIFIED_PATENT__ENGLISH_STOP_WORDS_SET = CharArraySet
				.unmodifiableSet(stopSet);
	}

}
